---
- name: Installer Docker sur les nodes
  hosts: nodes
  become: true
  tasks:

    - name: Mise à jour du système
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installer les dépendances
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Créer le dossier des clés
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Ajouter la clé GPG de Docker
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Donner les permissions à la clé
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Ajouter le dépôt Docker (Ubuntu 22.04 - jammy)
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable

    - name: Mise à jour des dépôts
      apt:
        update_cache: yes

    - name: Installer Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Activer et démarrer Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Ajouter l'utilisateur au groupe docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

